# workflows name show in action tag
name: Depoly Application

run-name: Depoly

# trigger for run workflow 
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: Select Branch For Depoly
        required: true
        default: main
        
jobs:
  depoly:
    runs-on: ubuntu-latest
    
    steps:
      # step1
      - name: Checkout The Repository
        uses: actions/checkout@v3
        
      # step2
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      # step3
      - name: Create Codedepoly for Deployment
        id: depoly
        run: |
          aws depoly create-deployment
          --application-name laravel-app-sample
          --deployment-group-name laravel-sample-gp-name
          --deployment-config-name CodeDepolyDefault.OneAtAtime
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
